from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

language = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='RU',callback_data='RU')
btn2 = InlineKeyboardButton(text='UZ',callback_data='UZ')
language.insert(btn1)
language.insert(btn2)

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Водно - дисперсионные акриловые краски',callback_data='menu_1')
btn2 = InlineKeyboardButton(text='Шпатлевки для дерева',callback_data='menu_2')
btn3 = InlineKeyboardButton(text='Эмали алкидные, грунтовки, разбавители',callback_data='menu_3')
btn4 = InlineKeyboardButton(text='Праймеры (грунт - пропитки)',callback_data='menu_4')
btn5 = InlineKeyboardButton(text='Декоративные штукатурки',callback_data='menu_5')
btn6 = InlineKeyboardButton(text='Пасты колерные - колоранты',callback_data='menu_6')
btn7 = InlineKeyboardButton(text='Декоративные и защитные лаки',callback_data='menu_7')
btn8 = InlineKeyboardButton(text='Эмали быстросохнущие',callback_data='menu_8')
btn9 = InlineKeyboardButton(text='Эмали с металлическим и молотковым эффектом',callback_data='menu_9')
btn10 = InlineKeyboardButton(text='Материал AQUASTOP',callback_data='menu_10')
btn11 = InlineKeyboardButton(text='Клей силикатный',callback_data='menu_11')
btn12 = InlineKeyboardButton(text='Назад',callback_data='back_to_lang')
menu.insert(btn1)
menu.insert(btn2)
menu.insert(btn3)
menu.insert(btn4)
menu.insert(btn5)
menu.insert(btn6)
menu.insert(btn7)
menu.insert(btn8)
menu.insert(btn9)
menu.insert(btn10)
menu.insert(btn11)
menu.insert(btn12)

menu_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Base - A Premium',callback_data='menu_1_1')
btn2 = InlineKeyboardButton(text='Silur Base - С Premium',callback_data='menu_1_2')
btn3 = InlineKeyboardButton(text='Super Plus Base - A',callback_data='menu_1_3')
btn4 = InlineKeyboardButton(text='Plus Base A',callback_data='menu_1_4')
btn5 = InlineKeyboardButton(text='Plus Base - C',callback_data='menu_1_5')
btn6 = InlineKeyboardButton(text='Olymp Универсальная',callback_data='menu_1_6')
btn7 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_1.insert(btn1)
menu_1.insert(btn2)
menu_1.insert(btn3)
menu_1.insert(btn4)
menu_1.insert(btn5)
menu_1.insert(btn6)
menu_1.insert(btn7)

menu_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Extra Class',callback_data='menu_2_1')
btn2 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_2.insert(btn1)
menu_2.insert(btn2)

menu_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='ЭМАЛЬ ПФ-115',callback_data='menu_3_1')
btn2 = InlineKeyboardButton(text='Для крыш',callback_data='menu_3_2')
btn3 = InlineKeyboardButton(text='Универсальная',callback_data='menu_3_3')
btn4 = InlineKeyboardButton(text='Для пола',callback_data='menu_3_4')
btn5 = InlineKeyboardButton(text='Эмаль ПФ-133',callback_data='menu_3_5')
btn6 = InlineKeyboardButton(text='Грунтовка ГФ-021',callback_data='menu_3_6')
btn7 = InlineKeyboardButton(text='Silur NS-ES',callback_data='menu_3_7')
btn8 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_3.insert(btn1)
menu_3.insert(btn2)
menu_3.insert(btn3)
menu_3.insert(btn4)
menu_3.insert(btn5)
menu_3.insert(btn6)
menu_3.insert(btn7)
menu_3.insert(btn8)

menu_4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Акриловый концентрат 1/7',callback_data='menu_4_1')
btn2 = InlineKeyboardButton(text='GRUNT-EC Акриловая',callback_data='menu_4_2')
btn3 = InlineKeyboardButton(text='Бетонконтакт',callback_data='menu_4_3')
btn4 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_4.insert(btn1)
menu_4.insert(btn2)
menu_4.insert(btn3)
menu_4.insert(btn4)

menu_5 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Хопёр',callback_data='menu_5_1')
btn2 = InlineKeyboardButton(text='Травертин',callback_data='menu_5_2')
btn3 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_5.insert(btn1)
menu_5.insert(btn2)
menu_5.insert(btn3)

menu_6 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Colorant EC',callback_data='menu_6_1')
btn2 = InlineKeyboardButton(text='Silur Colorant EC',callback_data='menu_6_2')
btn3 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_6.insert(btn1)
menu_6.insert(btn2)
menu_6.insert(btn3)

menu_7 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Extra Class Лак ПФ-283',callback_data='menu_7_1')
btn2 = InlineKeyboardButton(text='Silur Aulux Лак Aulux',callback_data='menu_7_2')
btn3 = InlineKeyboardButton(text='Silur Sealux Лак Sealux',callback_data='menu_7_3')
btn4 = InlineKeyboardButton(text='Silur Extra Class Лак цветной',callback_data='menu_7_4')
btn5 = InlineKeyboardButton(text='Silur Extra Class Лак БТ-577',callback_data='menu_7_5')
btn6 = InlineKeyboardButton(text='Silur Extra Class Лак Акриловый',callback_data='menu_7_6')
btn7 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_7.insert(btn1)
menu_7.insert(btn2)
menu_7.insert(btn3)
menu_7.insert(btn4)
menu_7.insert(btn5)
menu_7.insert(btn6)
menu_7.insert(btn7)


menu_8 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Эмаль МС-132',callback_data='menu_8_1')
btn2 = InlineKeyboardButton(text='Silur Extra Class Aqua-Plus',callback_data='menu_8_2')
btn3 = InlineKeyboardButton(text='Silur Extra Class',callback_data='menu_8_3')
btn4 = InlineKeyboardButton(text='Silur Extra Class',callback_data='menu_8_4')
btn5 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_8.insert(btn1)
menu_8.insert(btn2)
menu_8.insert(btn3)
menu_8.insert(btn4)
menu_8.insert(btn5)

menu_9 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Extra Class Серебристая',callback_data='menu_9_1')
btn2 = InlineKeyboardButton(text='Silur Hammer С молотковым эффектом',callback_data='menu_9_2')
btn3 = InlineKeyboardButton(text='Silur Hammer Brilliant С молотковым эффектом',callback_data='menu_9_3')
btn4 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_9.insert(btn1)
menu_9.insert(btn2)
menu_9.insert(btn3)
menu_9.insert(btn4)

menu_10 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Aquastop',callback_data='menu_10_1')
btn2 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_10.insert(btn1)
menu_10.insert(btn2)

menu_11 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Silur Extra Class Силикатный',callback_data='menu_11_1')
btn2 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
menu_11.insert(btn1)
menu_11.insert(btn2)

back = InlineKeyboardMarkup(row_width=1)
btn2 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
back.insert(btn1)
back.insert(btn2)